- client/package.json
- client/src/components/modal/closeChannel/CloseChannel.tsx
- client/src/components/modal/removePeer/RemovePeer.tsx
- client/src/graphql/mutation.ts
- client/src/graphql/query.ts
- client/src/sections/content/Content.tsx
- client/src/sections/navigation/Navigation.tsx
- client/src/views/channels/channels/ChannelCard.tsx
- client/src/views/channels/channels/Channels.tsx
- client/src/views/home/account/pay/pay.tsx
- client/src/views/peers/AddPeer.tsx
- client/src/views/peers/PeersCard.tsx
- client/src/views/peers/PeersList.tsx
- docs/LNDAPICoverage.md
- server/package.json
- server/src/schemas/mutations/index.ts
- server/src/schemas/mutations/peers/addPeer.ts
- server/src/schemas/mutations/peers/index.ts
- server/src/schemas/mutations/peers/removePeer.ts
- server/src/schemas/query/index.ts
- server/src/schemas/query/peer/getPeers.ts
- server/src/schemas/query/peer/getPeers.types.ts
- server/src/schemas/query/peer/index.ts
- server/src/utils/rateLimitConfig.ts
-   Add `getPeers` query
-   Add `addPeer` mutation
-   Add `removePeer` mutation
-   Add Peer view
-   Add `removePeer` modal
-   Add `addPeer` button
-   Update LND coverage doc
-   Organize Modal folder
-   Small Index Refactor
> feat: add peer queries mutations and views

- api/schemas/query/report/ForwardChannels.ts
- api/schemas/query/transactions/forwards.ts
Catching FullChannelDetailsNotFound on the getChannel call we do using the lightning library, this seems to be a response we get if the channel edge is not found or is a zombie one.
It seems the callback it's an array https://github.com/alexbosworth/lightning/blob/a713b58f0c1926cb926a77cdaf242ac2b4f31625/lnd_methods/info/get_channel.js#L64
We should join those calls into one so we avoid repeating code but for now this will fix the view that it's not showing at all.
fixes https://github.com/apotdevin/thunderhub/issues/45
> fix: catching getChannel callback error

- scripts/updateToLatest.sh
the update script did not recognise the difference between upstream an local when fetched and pulled in the same time.
> updateToLatest: fetch upstream before comparing

- pages/tools.tsx
- server/schema/bos/resolvers.ts
- server/schema/types.ts
- server/tests/__mocks__/balanceofsatoshis/balances.ts
- src/components/buttons/multiButton/MultiButton.tsx
- src/graphql/queries/__generated__/getAccountingReport.generated.tsx
- src/graphql/queries/getAccountingReport.ts
- src/graphql/types.ts
- src/utils/helpers.tsx
- src/views/balance/AdvancedBalance.tsx
- src/views/tools/Tools.styled.tsx
- src/views/tools/WalletVersion.tsx
- src/views/tools/accounting/Accounting.tsx
- ADD: accounting resolver
- ADD: `Accounting` component in `Tools` view
> feat: ✨ accounting

- server/helpers/__tests__/fileHelpers.test.ts
- server/helpers/fileHelpers.ts
We also add tests that verify you need to input either a master password
or an account password.
> bug: don't throw error on missing master password

- src/context/ConfigContext.tsx
- src/views/channels/channels/ChannelBars.tsx
- src/views/channels/channels/ChannelDetails.tsx
- src/views/channels/channels/ChannelManage.tsx
Currently, a channel larger than 16m is regarded as Wumbo. The limit is slightly higher than this.
> Change value limit of Wumbo channel to 16777215 sats

- src/client/src/views/home/account/pay/Pay.tsx
- src/server/modules/api/invoices/invoices.resolver.ts
This fixes issue #421.
- Changes the out value of the pay mutation from string array of node keys to string array of channel ids
- Changes lightning library prop from out to outgoing_channels so it isn't ignored when spread
> fix: Out Channels not respected for payments

- src/client/src/components/generic/helpers.tsx
- src/client/src/views/transactions/InvoiceCard.tsx
Fixes bug #152 by replacing 'ago' with 'from now' for future dated time in words strings on the Invoice card.
> Add 'from now' to time in words for future dated expiries

- src/server/main.ts
This PR addresses apotdevin#288 by letting the user specify the environment variable HOST to listen on a specific IP address, for example setting `HOST=127.0.0.1 npm run start`.
This change is backward compatible for users who do not set the `HOST` environment variable -- still will result in `undefined` being passed on to the javascript side as before.
This change is not backward compatible for users who have an environment variable `HOST` set in their runtime environment. (Not sure why they would have that set, given it is ignored by this application, but just pointing that out.)
Per node docs, https://nodejs.org/api/net.html#serverlisten: "If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address …
> Make host configurable in the same manner as port.

- src/client/pages/channels/[slug].tsx
- src/client/src/components/modal/changeDetails/ChangeDetails.tsx
- src/client/src/views/channels/channels/ChannelDetails.tsx
- src/client/src/views/channels/channels/ChannelTable.tsx
Include the channel name and id on the "Edit" modal in the same style that it's displayed on the "Close" modal. It's a nice reminder to the user of which channel they are currently editing and consistent with that information as it's displayed in the "Close" modal.
I also took the liberty of changing the toasts to refer to updating the channel "policy" instead of "fee" to reflect that a few of the parameters aren't fees. Let me know if you prefer not to make that change and I'll adjust the PR accordingly.
> Show channel name and id when editing channel policy

- src/client/src/views/home/reports/flow/TransactionGraph.tsx
The bar chart was showing incorrect tooltip on mouseover, so I fixed it (after navigating the code).
> fix: tooltip key in tx bar chart

- src/client/pages/amboss/index.tsx
- src/client/src/views/amboss/Backups.tsx
- src/client/src/views/amboss/Billboard.tsx
Added the ability to post to the Amboss.Space keysend billboard on the Amboss page. Users can now post messages without knowing the pubkey and without having to navigate to the Chat page.
> feat: add post to keysend billboard on amboss page

- schema.gql
- src/client/src/views/home/account/receiveOnChain/ReceiveOnChain.tsx
- src/server/modules/api/chain/chain.resolver.ts
Since v0.15.0, LND uses taproot addresses by default
This PR makes changes accordingly to match this update.
Src:
https://github.com/lightningnetwork/lnd/blob/v0-16-4-branch/docs/release-notes/release-notes-0.15.1.md#taproot
https://github.com/lightningnetwork/lnd/pull/6810
https://github.com/lightningnetwork/lnd/issues/6666
https://github.com/lightningnetwork/lnd/pull/6633
Ref:
https://github.com/apotdevin/thunderhub/commit/cb61a5073a0f67730704ffa55abb214fde8b0ec4
> [UPDATE] Change the default received onchain address to taproot

- src/client/src/views/channels/channels/ChannelTable.tsx
Notion: https://www.notion.so/amboss-tech/fceb1d1ddc024e40b4995547eda34502?v=8fe4ee4dabd545d596e1169eac79fcd1&p=a3324fe70b994c1491983a2979a6566f&pm=s
This fixes the table sorting functions on the Channels table that were missed during the package migration.
Fixes #556
> fix: channel table sorting fns

- src/client/src/components/version/Version.tsx
Changes the "updating" section documentation link reference to ThunderHub's web page. The old link points to this repository's README but there's no information for updating ThunderHub anymore.
Alternatively, it could point to the documentation repository: https://github.com/apotdevin/thunderhub-docs/blob/main/pages/installation.mdx
> Change updating documentation link

- src/client/pages/channels/[slug].tsx
- src/client/pages/forwards.tsx
- src/client/src/components/chart/ChannelChart.tsx
- src/client/src/components/select/index.tsx
For active channels, is sometimes great to see historical fee to decide new fee policy update.
Fee is calculated by eaach out (sent) transactions.
> add statistick to channel view

- src/server/config/configuration.ts
- src/server/modules/api/boltz/boltz.resolver.ts
I am not sure what changed, but the claim transactions that Thunderhub constructs right now are not created with the desired x sat/vbyte the user specifies but with x sat *absolute* fee.
This PR fixes the bug by using `targetFee` from `boltz-core` which allows specifying a sat/vbyte fee as parameter
> fix: Boltz swap claim transaction fees

- package.json
ThunderHub does not work with `nodejs` ^21.0.0 due to `echarts` dependency which at the same time had an issue with its `zrender` dependency.
- `echarts`: [issue](https://github.com/apache/echarts/issues/19233)
- `zrender`: [upstream pr](https://github.com/ecomfe/zrender/pull/1036)
Solved on `zrender` ^5.5.0, bump deps on `echarts` ^5.5.0
Issue description on #580
> bump dep, don't work with Node.js ^21.0.0 fix #580

- schema.gql
- src/client/src/graphql/queries/__generated__/getAmbossUser.generated.tsx
- src/client/src/graphql/queries/getAmbossUser.ts
- src/client/src/graphql/types.ts
- src/client/src/views/amboss/Backups.tsx
- src/server/modules/api/amboss/amboss.gql.ts
- src/server/modules/api/amboss/amboss.types.ts
- removed `available_size` and `remaining_size`
> refactor: replace deprecated fields

- src/client/src/views/home/liquidity/OpenChannel.tsx
Setting the channel Max Size to "Yes" by default should not be a good practice if you don't want to be surprised.
This is a PR to set the default Max Size setting to false (No) by default.
Before:
After:
> Set the "Max Size" setting to "false" (No) by default
